name: unigran_tcc
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  connectivity: ^0.4.3+7
  rxdart: ^0.25.0
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  dbcrypt: ^2.0.0
  image_picker: ^0.6.1+4
  cloud_firestore: ^0.5.0
  flutter_staggered_grid_view: ^0.3.3
  flutter_native_splash: ^1.1.8+4
  bloc_pattern: ^2.3.2
  provider: ^4.0.0
  brasil_fields: ^0.6.1
  validadores: ^1.0.2
  cpf_cnpj_validator: ^1.0.5
  mask_text_input_formatter: ^1.2.1
  google_fonts: ^1.0.0
  dropdown_search: ^0.4.9
  key_value_store_web: ^1.0.0
  jwt_decoder: ^1.0.3
  syncfusion_flutter_charts: ^18.4.39
  search_app_bar_page: ^1.4.2
  appbar_textfield: ^1.0.1+1
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  cron: ^0.3.0
  firebase: ^6.0.0
  image_web_picker: ^0.0.1
  image_picker_web: ^2.0.2
  universal_html: ^2.0.8
  firebase_core: ^0.4.1+3
  toast: ^0.1.5
  mime_type: ^1.0.0
  step_progress_indicator: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.2
  build_runner: ^1.11.0


flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/cardapio/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


